# Generated by Django 2.0 on 2018-03-31 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, verbose_name='Name')),
                ('price', models.FloatField(default=0, verbose_name='Price')),
                ('picture', models.ImageField(blank=True, upload_to='suppliers/goods', verbose_name='Picture')),
                ('description', models.TextField(blank=True, default=None, max_length=2048, verbose_name='Description')),
                ('rating', models.IntegerField(default=0, null=True, verbose_name='Rating')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
