# Generated by Django 2.0 on 2018-04-11 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_clients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='clients',
            new_name='members',
        ),
        migrations.AddField(
            model_name='clients',
            name='current_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
